on:
  push:
    branches: [ "mkulke/gha-test" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Code checkout
      uses: actions/checkout@v3

    - name: Rust toolchain installation
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: 1.69.0
        override: true
        default: false

    - name: rust version
      run: rustc --version
